import { Book } from "@/types";

export const BIBLE_BOOKS: Book[] = [
  // Old Testament
  { id: "GEN", name: "Genesis", abbreviation: "Gen", testament: "OT", chapters: 50 },
  { id: "EXO", name: "Exodus", abbreviation: "Exo", testament: "OT", chapters: 40 },
  { id: "LEV", name: "Leviticus", abbreviation: "Lev", testament: "OT", chapters: 27 },
  { id: "NUM", name: "Numbers", abbreviation: "Num", testament: "OT", chapters: 36 },
  { id: "DEU", name: "Deuteronomy", abbreviation: "Deu", testament: "OT", chapters: 34 },
  { id: "JOS", name: "Joshua", abbreviation: "Jos", testament: "OT", chapters: 24 },
  { id: "JDG", name: "Judges", abbreviation: "Jdg", testament: "OT", chapters: 21 },
  { id: "RUT", name: "Ruth", abbreviation: "Rut", testament: "OT", chapters: 4 },
  { id: "1SA", name: "1 Samuel", abbreviation: "1Sa", testament: "OT", chapters: 31 },
  { id: "2SA", name: "2 Samuel", abbreviation: "2Sa", testament: "OT", chapters: 24 },
  { id: "1KI", name: "1 Kings", abbreviation: "1Ki", testament: "OT", chapters: 22 },
  { id: "2KI", name: "2 Kings", abbreviation: "2Ki", testament: "OT", chapters: 25 },
  { id: "1CH", name: "1 Chronicles", abbreviation: "1Ch", testament: "OT", chapters: 29 },
  { id: "2CH", name: "2 Chronicles", abbreviation: "2Ch", testament: "OT", chapters: 36 },
  { id: "EZR", name: "Ezra", abbreviation: "Ezr", testament: "OT", chapters: 10 },
  { id: "NEH", name: "Nehemiah", abbreviation: "Neh", testament: "OT", chapters: 13 },
  { id: "EST", name: "Esther", abbreviation: "Est", testament: "OT", chapters: 10 },
  { id: "JOB", name: "Job", abbreviation: "Job", testament: "OT", chapters: 42 },
  { id: "PSA", name: "Psalms", abbreviation: "Psa", testament: "OT", chapters: 150 },
  { id: "PRO", name: "Proverbs", abbreviation: "Pro", testament: "OT", chapters: 31 },
  { id: "ECC", name: "Ecclesiastes", abbreviation: "Ecc", testament: "OT", chapters: 12 },
  { id: "SNG", name: "Song of Solomon", abbreviation: "Sng", testament: "OT", chapters: 8 },
  { id: "ISA", name: "Isaiah", abbreviation: "Isa", testament: "OT", chapters: 66 },
  { id: "JER", name: "Jeremiah", abbreviation: "Jer", testament: "OT", chapters: 52 },
  { id: "LAM", name: "Lamentations", abbreviation: "Lam", testament: "OT", chapters: 5 },
  { id: "EZK", name: "Ezekiel", abbreviation: "Ezk", testament: "OT", chapters: 48 },
  { id: "DAN", name: "Daniel", abbreviation: "Dan", testament: "OT", chapters: 12 },
  { id: "HOS", name: "Hosea", abbreviation: "Hos", testament: "OT", chapters: 14 },
  { id: "JOL", name: "Joel", abbreviation: "Jol", testament: "OT", chapters: 3 },
  { id: "AMO", name: "Amos", abbreviation: "Amo", testament: "OT", chapters: 9 },
  { id: "OBA", name: "Obadiah", abbreviation: "Oba", testament: "OT", chapters: 1 },
  { id: "JON", name: "Jonah", abbreviation: "Jon", testament: "OT", chapters: 4 },
  { id: "MIC", name: "Micah", abbreviation: "Mic", testament: "OT", chapters: 7 },
  { id: "NAM", name: "Nahum", abbreviation: "Nam", testament: "OT", chapters: 3 },
  { id: "HAB", name: "Habakkuk", abbreviation: "Hab", testament: "OT", chapters: 3 },
  { id: "ZEP", name: "Zephaniah", abbreviation: "Zep", testament: "OT", chapters: 3 },
  { id: "HAG", name: "Haggai", abbreviation: "Hag", testament: "OT", chapters: 2 },
  { id: "ZEC", name: "Zechariah", abbreviation: "Zec", testament: "OT", chapters: 14 },
  { id: "MAL", name: "Malachi", abbreviation: "Mal", testament: "OT", chapters: 4 },
  // New Testament
  { id: "MAT", name: "Matthew", abbreviation: "Mat", testament: "NT", chapters: 28 },
  { id: "MRK", name: "Mark", abbreviation: "Mrk", testament: "NT", chapters: 16 },
  { id: "LUK", name: "Luke", abbreviation: "Luk", testament: "NT", chapters: 24 },
  { id: "JHN", name: "John", abbreviation: "Jhn", testament: "NT", chapters: 21 },
  { id: "ACT", name: "Acts", abbreviation: "Act", testament: "NT", chapters: 28 },
  { id: "ROM", name: "Romans", abbreviation: "Rom", testament: "NT", chapters: 16 },
  { id: "1CO", name: "1 Corinthians", abbreviation: "1Co", testament: "NT", chapters: 16 },
  { id: "2CO", name: "2 Corinthians", abbreviation: "2Co", testament: "NT", chapters: 13 },
  { id: "GAL", name: "Galatians", abbreviation: "Gal", testament: "NT", chapters: 6 },
  { id: "EPH", name: "Ephesians", abbreviation: "Eph", testament: "NT", chapters: 6 },
  { id: "PHP", name: "Philippians", abbreviation: "Php", testament: "NT", chapters: 4 },
  { id: "COL", name: "Colossians", abbreviation: "Col", testament: "NT", chapters: 4 },
  { id: "1TH", name: "1 Thessalonians", abbreviation: "1Th", testament: "NT", chapters: 5 },
  { id: "2TH", name: "2 Thessalonians", abbreviation: "2Th", testament: "NT", chapters: 3 },
  { id: "1TI", name: "1 Timothy", abbreviation: "1Ti", testament: "NT", chapters: 6 },
  { id: "2TI", name: "2 Timothy", abbreviation: "2Ti", testament: "NT", chapters: 4 },
  { id: "TIT", name: "Titus", abbreviation: "Tit", testament: "NT", chapters: 3 },
  { id: "PHM", name: "Philemon", abbreviation: "Phm", testament: "NT", chapters: 1 },
  { id: "HEB", name: "Hebrews", abbreviation: "Heb", testament: "NT", chapters: 13 },
  { id: "JAS", name: "James", abbreviation: "Jas", testament: "NT", chapters: 5 },
  { id: "1PE", name: "1 Peter", abbreviation: "1Pe", testament: "NT", chapters: 5 },
  { id: "2PE", name: "2 Peter", abbreviation: "2Pe", testament: "NT", chapters: 3 },
  { id: "1JN", name: "1 John", abbreviation: "1Jn", testament: "NT", chapters: 5 },
  { id: "2JN", name: "2 John", abbreviation: "2Jn", testament: "NT", chapters: 1 },
  { id: "3JN", name: "3 John", abbreviation: "3Jn", testament: "NT", chapters: 1 },
  { id: "JUD", name: "Jude", abbreviation: "Jud", testament: "NT", chapters: 1 },
  { id: "REV", name: "Revelation", abbreviation: "Rev", testament: "NT", chapters: 22 },
];

export const BOOK_BY_ID = Object.fromEntries(BIBLE_BOOKS.map((b) => [b.id, b]));

export const OT_BOOKS = BIBLE_BOOKS.filter((b) => b.testament === "OT");
export const NT_BOOKS = BIBLE_BOOKS.filter((b) => b.testament === "NT");
