const VERSES = [
  { text: "Wherewithal shall a young man cleanse his way? By taking heed thereto according to thy word.", ref: "Psalm 119:9", translation: "KJV" },
  { text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding.", ref: "Proverbs 3:5", translation: "KJV" },
  { text: "I can do all things through Christ which strengtheneth me.", ref: "Philippians 4:13", translation: "KJV" },
  { text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", ref: "John 3:16", translation: "KJV" },
  { text: "The LORD is my shepherd; I shall not want.", ref: "Psalm 23:1", translation: "KJV" },
  { text: "Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.", ref: "Joshua 1:9", translation: "NIV" },
  { text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", ref: "Romans 8:28", translation: "NIV" },
  { text: "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.", ref: "Jeremiah 29:11", translation: "NIV" },
  { text: "Come to me, all you who are weary and burdened, and I will give you rest.", ref: "Matthew 11:28", translation: "NIV" },
  { text: "The LORD bless thee, and keep thee: the LORD make his face shine upon thee, and be gracious unto thee.", ref: "Numbers 6:24–25", translation: "KJV" },
  { text: "Thy word is a lamp unto my feet, and a light unto my path.", ref: "Psalm 119:105", translation: "KJV" },
  { text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles.", ref: "Isaiah 40:31", translation: "KJV" },
  { text: "Cast all your anxiety on him because he cares for you.", ref: "1 Peter 5:7", translation: "NIV" },
  { text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", ref: "Philippians 4:6", translation: "NIV" },
  { text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?", ref: "Psalm 27:1", translation: "KJV" },
  { text: "In the beginning God created the heaven and the earth.", ref: "Genesis 1:1", translation: "KJV" },
  { text: "Jesus said unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.", ref: "John 14:6", translation: "KJV" },
  { text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", ref: "1 Corinthians 13:4", translation: "NIV" },
  { text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.", ref: "Ephesians 2:8", translation: "KJV" },
  { text: "Create in me a clean heart, O God; and renew a right spirit within me.", ref: "Psalm 51:10", translation: "KJV" },
  { text: "The peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.", ref: "Philippians 4:7", translation: "ESV" },
  { text: "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven.", ref: "2 Chronicles 7:14", translation: "KJV" },
  { text: "Greater love hath no man than this, that a man lay down his life for his friends.", ref: "John 15:13", translation: "KJV" },
  { text: "The grass withereth, the flower fadeth: but the word of our God shall stand for ever.", ref: "Isaiah 40:8", translation: "KJV" },
  { text: "Delight thyself also in the LORD: and he shall give thee the desires of thine heart.", ref: "Psalm 37:4", translation: "KJV" },
  { text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee.", ref: "Isaiah 41:10", translation: "KJV" },
  { text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.", ref: "Matthew 7:7", translation: "KJV" },
  { text: "He giveth power to the faint; and to them that have no might he increaseth strength.", ref: "Isaiah 40:29", translation: "KJV" },
  { text: "Search me, O God, and know my heart: try me, and know my thoughts.", ref: "Psalm 139:23", translation: "KJV" },
  { text: "I have been crucified with Christ and I no longer live, but Christ lives in me.", ref: "Galatians 2:20", translation: "NIV" },
  { text: "Be still, and know that I am God.", ref: "Psalm 46:10", translation: "KJV" },
  { text: "No weapon that is formed against thee shall prosper.", ref: "Isaiah 54:17", translation: "KJV" },
  { text: "Rejoice in the Lord always: and again I say, Rejoice.", ref: "Philippians 4:4", translation: "KJV" },
  { text: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth.", ref: "Psalm 145:18", translation: "KJV" },
  { text: "In the beginning was the Word, and the Word was with God, and the Word was God.", ref: "John 1:1", translation: "KJV" },
  { text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", ref: "2 Timothy 1:7", translation: "KJV" },
  { text: "This is the day which the LORD hath made; we will rejoice and be glad in it.", ref: "Psalm 118:24", translation: "KJV" },
  { text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", ref: "Matthew 6:33", translation: "KJV" },
  { text: "Blessed are the pure in heart: for they shall see God.", ref: "Matthew 5:8", translation: "KJV" },
  { text: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe.", ref: "Proverbs 18:10", translation: "KJV" },
  { text: "O give thanks unto the LORD; for he is good: for his mercy endureth for ever.", ref: "Psalm 136:1", translation: "KJV" },
  { text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.", ref: "Matthew 5:16", translation: "KJV" },
  { text: "Though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me.", ref: "Psalm 23:4", translation: "KJV" },
  { text: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.", ref: "1 John 1:9", translation: "KJV" },
  { text: "Now faith is the substance of things hoped for, the evidence of things not seen.", ref: "Hebrews 11:1", translation: "KJV" },
  { text: "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD.", ref: "Psalm 121:1–2", translation: "KJV" },
  { text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness.", ref: "2 Corinthians 12:9", translation: "KJV" },
  { text: "Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee.", ref: "Exodus 20:12", translation: "KJV" },
  { text: "Pray without ceasing.", ref: "1 Thessalonians 5:17", translation: "KJV" },
  { text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, shall be able to separate us from the love of God.", ref: "Romans 8:38–39", translation: "KJV" },
  { text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.", ref: "Galatians 5:22", translation: "KJV" },
  { text: "A soft answer turneth away wrath: but grievous words stir up anger.", ref: "Proverbs 15:1", translation: "KJV" },
  { text: "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over.", ref: "Luke 6:38", translation: "KJV" },
  { text: "Draw nigh to God, and he will draw nigh to you.", ref: "James 4:8", translation: "KJV" },
  { text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil.", ref: "Psalm 23:4", translation: "KJV" },
  { text: "The LORD is my strength and my shield; my heart trusted in him, and I am helped.", ref: "Psalm 28:7", translation: "KJV" },
  { text: "But as for me and my house, we will serve the LORD.", ref: "Joshua 24:15", translation: "KJV" },
  { text: "With men this is impossible; but with God all things are possible.", ref: "Matthew 19:26", translation: "KJV" },
  { text: "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful.", ref: "Psalm 1:1", translation: "KJV" },
  { text: "Have I not commanded you? Be strong and courageous. Do not be frightened, and do not be dismayed, for the LORD your God is with you wherever you go.", ref: "Joshua 1:9", translation: "ESV" },
  { text: "He heals the brokenhearted and binds up their wounds.", ref: "Psalm 147:3", translation: "NIV" },
  { text: "Your word I have hidden in my heart, that I might not sin against You.", ref: "Psalm 119:11", translation: "NKJV" },
  { text: "The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness.", ref: "Zephaniah 3:17", translation: "ESV" },
];

export function getVerseOfTheDay() {
  const dayIndex = Math.floor(Date.now() / 86_400_000);
  return VERSES[dayIndex % VERSES.length];
}
